# Generated by Django 4.2 on 2023-09-22 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitness', '0003_product_cartitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='type',
            field=models.CharField(default='default_value_here', max_length=100),
        ),
    ]
